controller_list:
  - name: fake_arm_controller
    joints:
      - base__link_01
      - link_01__link_02
      - link_02__link_03
      - link_03__link_04
      - link_04__link_05
  - name: fake_gripper_controller
    joints:
      - link_05__gripper_01
      - link_05__gripper_02